from animation.parameters_generator.DiffusionParameters import DiffusionParameters
from animation.parameters_generator.GenerationParameters import GenerationParameters
from animation.parameters_generator.InitImageGenerator import InitImageGenerator